# Agent configuration
agent:
  use_prompts_yaml: false
  planning_interval: 6
  max_steps: 50
  additional_authorized_imports: ["*"]

llm:
  provider: "openrouter"
  api_base: "https://openrouter.ai/api/v1"
  api_key: "YOUR_API_KEY_HERE"
  model: "openrouter/optimus-alpha"

# llm:
#   provider: "litellm"
#   api_base: "http://your-litellm-endpoint"
#   api_key: "YOUR_API_KEY_HERE"
#   model: "claude-3-7-load-balance"
#   temperature: 0.7
#   max_tokens: 20000

# Docker sandbox configuration
docker:
  image_name: "sandbox-image"
  port: 7860
  agent_script: "examples/cli_agent.py"
  dockerfile_path: "."
  working_dir: "/app"
  data_dir: "/data"  # Directory for writable data
  force_rebuild: false  # Whether to force rebuilding the image
